// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EduVi.Repositories.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.DBContext;

public partial class EduViContext : DbContext
{
    public EduViContext()
    {
    }

    public EduViContext(DbContextOptions<EduViContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Admins> Admins { get; set; }

    public virtual DbSet<Chapters> Chapters { get; set; }

    public virtual DbSet<Experts> Experts { get; set; }

    public virtual DbSet<Grades> Grades { get; set; }

    public virtual DbSet<InputDocuments> InputDocuments { get; set; }

    public virtual DbSet<Materials> Materials { get; set; }

    public virtual DbSet<Orders> Orders { get; set; }

    public virtual DbSet<ProductComponent> ProductComponent { get; set; }

    public virtual DbSet<Products> Products { get; set; }

    public virtual DbSet<Projects> Projects { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<Staffs> Staffs { get; set; }

    public virtual DbSet<Subjects> Subjects { get; set; }

    public virtual DbSet<SubscriptionPlans> SubscriptionPlans { get; set; }

    public virtual DbSet<SystemLogs> SystemLogs { get; set; }

    public virtual DbSet<TeacherMaterials> TeacherMaterials { get; set; }

    public virtual DbSet<Teachers> Teachers { get; set; }

    public virtual DbSet<UserQuotas> UserQuotas { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    public virtual DbSet<Wallets> Wallets { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection")).UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Admins>(entity =>
        {
            entity.HasKey(e => e.AdminId).HasName("PK__Admins__719FE4E8D1BDB6CF");

            entity.Property(e => e.AdminId)
                .ValueGeneratedNever()
                .HasColumnName("AdminID");

            entity.HasOne(d => d.Admin).WithOne(p => p.Admins)
                .HasForeignKey<Admins>(d => d.AdminId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Admins_Users");
        });

        modelBuilder.Entity<Chapters>(entity =>
        {
            entity.HasKey(e => e.ChapterId).HasName("PK__Chapters__0893A34ABEF40482");

            entity.Property(e => e.ChapterId).HasColumnName("ChapterID");
            entity.Property(e => e.ChapterName).HasMaxLength(100);
            entity.Property(e => e.SubjectId).HasColumnName("SubjectID");

            entity.HasOne(d => d.Subject).WithMany(p => p.Chapters)
                .HasForeignKey(d => d.SubjectId)
                .HasConstraintName("FK_Chapters_Subjects");
        });

        modelBuilder.Entity<Experts>(entity =>
        {
            entity.HasKey(e => e.ExpertId).HasName("PK__Experts__7EDB3A38A6FA8802");

            entity.Property(e => e.ExpertId)
                .ValueGeneratedNever()
                .HasColumnName("ExpertID");
            entity.Property(e => e.BankAccount)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.BankName).HasMaxLength(100);
            entity.Property(e => e.IdentityCardNumber)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.IsVerified).HasDefaultValue(false);
            entity.Property(e => e.TaxCode)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Expert).WithOne(p => p.Experts)
                .HasForeignKey<Experts>(d => d.ExpertId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Experts_Users");
        });

        modelBuilder.Entity<Grades>(entity =>
        {
            entity.HasKey(e => e.GradeId).HasName("PK__Grades__54F87A37628EAD42");

            entity.Property(e => e.GradeId).HasColumnName("GradeID");
            entity.Property(e => e.GradeName).HasMaxLength(50);
        });

        modelBuilder.Entity<InputDocuments>(entity =>
        {
            entity.HasKey(e => e.DocumentId).HasName("PK__InputDoc__1ABEEF6FB9B9B79B");

            entity.Property(e => e.DocumentId).HasColumnName("DocumentID");
            entity.Property(e => e.ChapterId).HasColumnName("ChapterID");
            entity.Property(e => e.FilePath)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.GradeId).HasColumnName("GradeID");
            entity.Property(e => e.Raw).HasMaxLength(500);
            entity.Property(e => e.SubjectId).HasColumnName("SubjectID");
            entity.Property(e => e.TeacherId).HasColumnName("TeacherID");
            entity.Property(e => e.Title).HasMaxLength(200);
            entity.Property(e => e.UploadDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Chapter).WithMany(p => p.InputDocuments)
                .HasForeignKey(d => d.ChapterId)
                .HasConstraintName("FK__InputDocu__Chapt__5812160E");

            entity.HasOne(d => d.Grade).WithMany(p => p.InputDocuments)
                .HasForeignKey(d => d.GradeId)
                .HasConstraintName("FK__InputDocu__Grade__571DF1D5");

            entity.HasOne(d => d.Subject).WithMany(p => p.InputDocuments)
                .HasForeignKey(d => d.SubjectId)
                .HasConstraintName("FK__InputDocu__Subje__5629CD9C");

            entity.HasOne(d => d.Teacher).WithMany(p => p.InputDocuments)
                .HasForeignKey(d => d.TeacherId)
                .HasConstraintName("FK__InputDocu__Teach__5535A963");
        });

        modelBuilder.Entity<Materials>(entity =>
        {
            entity.HasKey(e => e.MaterialId).HasName("PK__Material__C5061317F8305590");

            entity.Property(e => e.MaterialId).HasColumnName("MaterialID");
            entity.Property(e => e.ApprovalStatus).HasDefaultValue(0);
            entity.Property(e => e.ApproverId).HasColumnName("ApproverID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpertId).HasColumnName("ExpertID");
            entity.Property(e => e.GradeId).HasColumnName("GradeID");
            entity.Property(e => e.PreviewUrl)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ResourceUrl)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.SubjectId).HasColumnName("SubjectID");
            entity.Property(e => e.Title).HasMaxLength(200);
            entity.Property(e => e.Type)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Approver).WithMany(p => p.Materials)
                .HasForeignKey(d => d.ApproverId)
                .HasConstraintName("FK__Materials__Appro__5DCAEF64");

            entity.HasOne(d => d.Expert).WithMany(p => p.Materials)
                .HasForeignKey(d => d.ExpertId)
                .HasConstraintName("FK__Materials__Exper__5CD6CB2B");

            entity.HasOne(d => d.Grade).WithMany(p => p.Materials)
                .HasForeignKey(d => d.GradeId)
                .HasConstraintName("FK__Materials__Grade__5FB337D6");

            entity.HasOne(d => d.Subject).WithMany(p => p.Materials)
                .HasForeignKey(d => d.SubjectId)
                .HasConstraintName("FK__Materials__Subje__5EBF139D");
        });

        modelBuilder.Entity<Orders>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Orders__C3905BAF4B2255D1");

            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.OrderDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PaymentMethod)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Status).HasDefaultValue(0);
            entity.Property(e => e.TeacherId).HasColumnName("TeacherID");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Teacher).WithMany(p => p.Orders)
                .HasForeignKey(d => d.TeacherId)
                .HasConstraintName("FK__Orders__TeacherI__08B54D69");
        });

        modelBuilder.Entity<ProductComponent>(entity =>
        {
            entity.HasKey(e => new { e.ProductId, e.MaterialId }).HasName("PK__ProductC__D85CA7DC61DABA12");

            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.MaterialId).HasColumnName("MaterialID");
            entity.Property(e => e.TeacherId).HasColumnName("TeacherID");

            entity.HasOne(d => d.Products).WithMany(p => p.ProductComponent)
                .HasPrincipalKey(p => new { p.ProductId, p.TeacherId })
                .HasForeignKey(d => new { d.ProductId, d.TeacherId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PC_Products");

            entity.HasOne(d => d.TeacherMaterials).WithMany(p => p.ProductComponent)
                .HasForeignKey(d => new { d.TeacherId, d.MaterialId })
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PC_TeacherMaterials");
        });

        modelBuilder.Entity<Products>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK__Products__B40CC6ED21E0E3A0");

            entity.HasIndex(e => new { e.ProductId, e.TeacherId }, "UQ_Products_Teacher").IsUnique();

            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.IsFreeForSubscribers).HasDefaultValue(false);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ProductName).HasMaxLength(200);
            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.SourceInputId).HasColumnName("SourceInputID");
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.TeacherId).HasColumnName("TeacherID");

            entity.HasOne(d => d.Project).WithMany(p => p.Products)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Products__Projec__6EF57B66");

            entity.HasOne(d => d.Teacher).WithMany(p => p.Products)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Products__Teache__6FE99F9F");
        });

        modelBuilder.Entity<Projects>(entity =>
        {
            entity.HasKey(e => e.ProjectId).HasName("PK__Projects__761ABED03237E04E");

            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.Deadline).HasColumnType("datetime");
            entity.Property(e => e.InputDocumentId).HasColumnName("InputDocumentID");
            entity.Property(e => e.ProjectName).HasMaxLength(200);
            entity.Property(e => e.StartDate).HasColumnType("datetime");
            entity.Property(e => e.Status).HasDefaultValue(0);
            entity.Property(e => e.TeacherId).HasColumnName("TeacherID");

            entity.HasOne(d => d.InputDocument).WithMany(p => p.Projects)
                .HasForeignKey(d => d.InputDocumentId)
                .HasConstraintName("FK__Projects__InputD__693CA210");

            entity.HasOne(d => d.Teacher).WithMany(p => p.Projects)
                .HasForeignKey(d => d.TeacherId)
                .HasConstraintName("FK__Projects__Teache__68487DD7");
        });

        modelBuilder.Entity<Roles>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__8AFACE3ADD4643BD");

            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Staffs>(entity =>
        {
            entity.HasKey(e => e.StaffId).HasName("PK__Staffs__96D4AAF751264458");

            entity.HasIndex(e => e.StaffCode, "UQ__Staffs__D83AD812B1EC83D6").IsUnique();

            entity.Property(e => e.StaffId)
                .ValueGeneratedNever()
                .HasColumnName("StaffID");
            entity.Property(e => e.Department).HasMaxLength(100);
            entity.Property(e => e.StaffCode)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Staff).WithOne(p => p.Staffs)
                .HasForeignKey<Staffs>(d => d.StaffId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Staffs_Users");
        });

        modelBuilder.Entity<Subjects>(entity =>
        {
            entity.HasKey(e => e.SubjectId).HasName("PK__Subjects__AC1BA38865AA8D90");

            entity.Property(e => e.SubjectId).HasColumnName("SubjectID");
            entity.Property(e => e.Code)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.SubjectName).HasMaxLength(100);
        });

        modelBuilder.Entity<SubscriptionPlans>(entity =>
        {
            entity.HasKey(e => e.PlanId).HasName("PK__Subscrip__755C22D74FC00743");

            entity.Property(e => e.PlanId).HasColumnName("PlanID");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PlanName).HasMaxLength(100);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
        });

        modelBuilder.Entity<SystemLogs>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__SystemLo__5E5499A841E26CA0");

            entity.Property(e => e.LogId).HasColumnName("LogID");
            entity.Property(e => e.Action).HasMaxLength(100);
            entity.Property(e => e.Ipaddress)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("IPAddress");
            entity.Property(e => e.Timestamp)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithMany(p => p.SystemLogs)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK__SystemLog__UserI__0C85DE4D");
        });

        modelBuilder.Entity<TeacherMaterials>(entity =>
        {
            entity.HasKey(e => new { e.TeacherId, e.MaterialId }).HasName("PK__TeacherM__81A2387567765723");

            entity.Property(e => e.TeacherId).HasColumnName("TeacherID");
            entity.Property(e => e.MaterialId).HasColumnName("MaterialID");
            entity.Property(e => e.PurchasedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Material).WithMany(p => p.TeacherMaterials)
                .HasForeignKey(d => d.MaterialId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TeacherMa__Mater__6477ECF3");

            entity.HasOne(d => d.Teacher).WithMany(p => p.TeacherMaterials)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TeacherMa__Teach__6383C8BA");
        });

        modelBuilder.Entity<Teachers>(entity =>
        {
            entity.HasKey(e => e.TeacherId).HasName("PK__Teachers__EDF25944C8B89D82");

            entity.Property(e => e.TeacherId)
                .ValueGeneratedNever()
                .HasColumnName("TeacherID");
            entity.Property(e => e.Degree).HasMaxLength(100);
            entity.Property(e => e.SchoolName).HasMaxLength(100);

            entity.HasOne(d => d.Teacher).WithOne(p => p.Teachers)
                .HasForeignKey<Teachers>(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Teachers_Users");
        });

        modelBuilder.Entity<UserQuotas>(entity =>
        {
            entity.HasKey(e => e.UserQuotaId).HasName("PK__UserQuot__94C6F707A1BAB374");

            entity.HasIndex(e => e.TeacherId, "UQ__UserQuot__EDF25945AE47A83B").IsUnique();

            entity.Property(e => e.UserQuotaId).HasColumnName("UserQuotaID");
            entity.Property(e => e.AvailableQuota).HasDefaultValue(0);
            entity.Property(e => e.TeacherId).HasColumnName("TeacherID");
            entity.Property(e => e.TotalQuota).HasDefaultValue(0);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UsedQuota).HasDefaultValue(0);

            entity.HasOne(d => d.Teacher).WithOne(p => p.UserQuotas)
                .HasForeignKey<UserQuotas>(d => d.TeacherId)
                .HasConstraintName("FK__UserQuota__Teach__03F0984C");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCAC75DD0666");

            entity.HasIndex(e => e.Email, "IX_Users_Email");

            entity.HasIndex(e => e.Username, "UQ__Users__536C85E49221B0F6").IsUnique();

            entity.HasIndex(e => e.Email, "UQ__Users__A9D10534C19D49D1").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.AvatarUrl)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("AvatarURL");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FullName).HasMaxLength(100);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Users_Roles");
        });

        modelBuilder.Entity<Wallets>(entity =>
        {
            entity.HasKey(e => e.WalletId).HasName("PK__Wallets__84D4F92EAE7BB1F6");

            entity.HasIndex(e => e.UserId, "UQ__Wallets__1788CCADD1E95214").IsUnique();

            entity.Property(e => e.WalletId).HasColumnName("WalletID");
            entity.Property(e => e.Balance)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LastUpdated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithOne(p => p.Wallets)
                .HasForeignKey<Wallets>(d => d.UserId)
                .HasConstraintName("FK__Wallets__UserID__797309D9");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}