// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EduVi.Repositories.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.DBContext;

public partial class EduViContext : DbContext
{
    public EduViContext()
    {
    }

    public EduViContext(DbContextOptions<EduViContext> options)
        : base(options)
    {
    }

    public virtual DbSet<StudentLists> StudentLists { get; set; }

    public virtual DbSet<Admins> Admins { get; set; }

    public virtual DbSet<Lessons> Lessons { get; set; }

    public virtual DbSet<Experts> Experts { get; set; }

    public virtual DbSet<ExpertVerifications> ExpertVerifications { get; set; }

    public virtual DbSet<Grades> Grades { get; set; }

    public virtual DbSet<GameTemplates> GameTemplates { get; set; }

    public virtual DbSet<CardTemplates> CardTemplates { get; set; }

    public virtual DbSet<ProductGames> ProductGames { get; set; }

    public virtual DbSet<InputDocuments> InputDocuments { get; set; }

    public virtual DbSet<Materials> Materials { get; set; }

    public virtual DbSet<Orders> Orders { get; set; }

    public virtual DbSet<Products> Products { get; set; }

    public virtual DbSet<ProductVideos> ProductVideos { get; set; }

    public virtual DbSet<CurriculumDocuments> CurriculumDocuments { get; set; }

    public virtual DbSet<TextbookDocuments> TextbookDocuments { get; set; }

    public virtual DbSet<Projects> Projects { get; set; }

    public virtual DbSet<Roles> Roles { get; set; }

    public virtual DbSet<Staffs> Staffs { get; set; }

    public virtual DbSet<Subjects> Subjects { get; set; }

    public virtual DbSet<QuotaPlans> QuotaPlans { get; set; }

    public virtual DbSet<TeacherMaterials> TeacherMaterials { get; set; }

    public virtual DbSet<Teachers> Teachers { get; set; }

    public virtual DbSet<UserQuotas> UserQuotas { get; set; }

    public virtual DbSet<Users> Users { get; set; }

    public virtual DbSet<Wallets> Wallets { get; set; }

    public virtual DbSet<WalletTransactions> WalletTransactions { get; set; }

    public virtual DbSet<WithdrawalRequests> WithdrawalRequests { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        // OnConfiguring is called even when options are configured via DI (Program.cs).
        // Only fall back to appsettings.json when no options have been provided —
        // this covers design-time tools (dotnet ef migrations) on a developer machine.
        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection"));
        }
        optionsBuilder.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
    }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Admins>(entity =>
        {
            entity.HasKey(e => e.AdminId).HasName("PK__Admins__719FE4E8D1BDB6CF");

            entity.HasIndex(e => e.AdminCode, "UQ__Admins__AdminCode").IsUnique();

            entity.Property(e => e.AdminId)
                .ValueGeneratedNever()
                .HasColumnName("AdminID");
            entity.Property(e => e.AdminCode)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Admin).WithOne(p => p.Admins)
                .HasForeignKey<Admins>(d => d.AdminId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Admins_Users");
        });

        modelBuilder.Entity<Lessons>(entity =>
        {
            entity.HasKey(e => e.LessonId).HasName("PK__Chapters__0893A34ABEF40482");

            entity.ToTable("Lessons");

            entity.Property(e => e.LessonId).HasColumnName("LessonID");
            entity.Property(e => e.LessonCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("LessonCode");
            entity.Property(e => e.LessonName).HasMaxLength(100);
            entity.Property(e => e.SubjectId).HasColumnName("SubjectID");

            entity.HasOne(d => d.Subject).WithMany(p => p.Lessons)
                .HasForeignKey(d => d.SubjectId)
                .HasConstraintName("FK_Chapters_Subjects");
        });

        modelBuilder.Entity<Experts>(entity =>
        {
            entity.HasKey(e => e.ExpertId).HasName("PK__Experts__7EDB3A38A6FA8802");

            entity.HasIndex(e => e.ExpertCode, "UQ__Experts__ExpertCode").IsUnique();

            entity.Property(e => e.ExpertId)
                .ValueGeneratedNever()
                .HasColumnName("ExpertID");
            entity.Property(e => e.ExpertCode)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.IsVerified).HasDefaultValue(false);

            entity.HasOne(d => d.Expert).WithOne(p => p.Experts)
                .HasForeignKey<Experts>(d => d.ExpertId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Experts_Users");
        });

        modelBuilder.Entity<ExpertVerifications>(entity =>
        {
            entity.HasKey(e => e.VerificationId).HasName("PK_ExpertVerifications");

            entity.HasIndex(e => e.VerificationCode, "UQ_ExpertVerifications_Code").IsUnique();
            entity.HasIndex(e => e.ExpertId, "IX_ExpertVerifications_ExpertId");
            entity.HasIndex(e => e.Status, "IX_ExpertVerifications_Status");

            entity.Property(e => e.VerificationCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FileUrl).HasMaxLength(500);
            entity.Property(e => e.FileType).HasMaxLength(50);
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Status)
                .HasDefaultValue(0);
            entity.Property(e => e.RejectionReason).HasMaxLength(500);
            entity.Property(e => e.UploadedAt).HasDefaultValueSql("GETUTCDATE()");

            entity.HasOne(d => d.Expert)
                .WithMany()
                .HasForeignKey(d => d.ExpertId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_ExpertVerifications_Expert");

            entity.HasOne(d => d.ReviewedByStaff)
                .WithMany()
                .HasForeignKey(d => d.ReviewedByStaffId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ExpertVerifications_Staff");
        });

        modelBuilder.Entity<Grades>(entity =>
        {
            entity.HasKey(e => e.GradeId).HasName("PK__Grades__54F87A37628EAD42");

            entity.Property(e => e.GradeId).HasColumnName("GradeID");
            entity.Property(e => e.GradeCode)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("GradeCode");
            entity.Property(e => e.GradeName).HasMaxLength(50);
        });

        modelBuilder.Entity<GameTemplates>(entity =>
        {
            entity.HasKey(e => e.TemplateId).HasName("PK__GameTemp__2F02A8A6A8D4A6E1");

            entity.HasIndex(e => e.TemplateCode, "UQ_GameTemplates_TemplateCode").IsUnique();

            entity.ToTable("GameTemplates");

            entity.Property(e => e.TemplateId)
                .HasColumnName("id")
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TemplateCode)
                .HasColumnName("template_code")
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TemplateJson)
                .HasColumnName("template_json")
                .HasColumnType("nvarchar(max)");
        });

        modelBuilder.Entity<CardTemplates>(entity =>
        {
            entity.ToTable("CardTemplates");

            entity.HasKey(e => e.TemplateId).HasName("PK_CardTemplates");
            entity.HasIndex(e => e.TemplateCode, "UQ_CardTemplates_TemplateCode").IsUnique();

            entity.Property(e => e.TemplateId).HasColumnName("TemplateID");
            entity.Property(e => e.TemplateCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Name).HasMaxLength(200);
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Category)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Skeleton).HasColumnType("nvarchar(max)");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime2")
                .HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.UpdatedAt)
                .HasColumnType("datetime2")
                .HasDefaultValueSql("GETUTCDATE()");
        });

        modelBuilder.Entity<ProductGames>(entity =>
        {
            entity.ToTable("ProductGames");

            entity.HasKey(e => e.ProductGameId).HasName("PK_ProductGames");

            entity.HasIndex(e => e.ProductGameCode, "UQ_ProductGames_ProductGameCode").IsUnique();
            entity.HasIndex(e => e.TaskId, "UQ_ProductGames_TaskId").IsUnique();
            entity.HasIndex(e => new { e.ProductId, e.CreatedAt }, "IX_ProductGames_ProductId_CreatedAt");

            entity.Property(e => e.ProductGameId).HasColumnName("ProductGameID");
            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.ProductGameCode)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ProductGameName)
                .HasMaxLength(200)
                .HasColumnName("ProductName");
            entity.Property(e => e.TemplateCode)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Status).HasDefaultValue(0);
            entity.Property(e => e.ResultJson).HasColumnType("nvarchar(max)");
            entity.Property(e => e.ErrorMessage).HasMaxLength(2000);
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime2")
                .HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime2");
            entity.Property(e => e.CompletedAt).HasColumnType("datetime2");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductGames)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_ProductGames_Products");
        });

        modelBuilder.Entity<InputDocuments>(entity =>
        {
            entity.HasKey(e => e.DocumentId).HasName("PK__InputDoc__1ABEEF6FB9B9B79B");

            entity.Property(e => e.DocumentId).HasColumnName("DocumentID");
            entity.Property(e => e.LessonId).HasColumnName("LessonID");
            entity.Property(e => e.DocumentCode)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("DocumentCode");
            entity.Property(e => e.FilePath)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.GradeId).HasColumnName("GradeID");

            entity.Property(e => e.SubjectId).HasColumnName("SubjectID");
            entity.Property(e => e.TeacherId).HasColumnName("TeacherID");
            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.Title).HasMaxLength(200);
            entity.Property(e => e.UploadDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Status).HasDefaultValue(0);

            entity.HasOne(d => d.Lesson).WithMany(p => p.InputDocuments)
                .HasForeignKey(d => d.LessonId)
                .HasConstraintName("FK__InputDocu__Chapt__5812160E");

            entity.HasOne(d => d.Grade).WithMany(p => p.InputDocuments)
                .HasForeignKey(d => d.GradeId)
                .HasConstraintName("FK__InputDocu__Grade__571DF1D5");

            entity.HasOne(d => d.Subject).WithMany(p => p.InputDocuments)
                .HasForeignKey(d => d.SubjectId)
                .HasConstraintName("FK__InputDocu__Subje__5629CD9C");

            entity.HasOne(d => d.Teacher).WithMany(p => p.InputDocuments)
                .HasForeignKey(d => d.TeacherId)
                .HasConstraintName("FK__InputDocu__Teach__5535A963");

            entity.HasOne(d => d.Project).WithMany(p => p.InputDocuments)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("FK__InputDocu__Proje__ProjectID");
        });

        modelBuilder.Entity<Materials>(entity =>
        {
            entity.HasKey(e => e.MaterialId).HasName("PK__Material__C5061317F8305590");

            entity.Property(e => e.MaterialId).HasColumnName("MaterialID");
            entity.Property(e => e.ApprovalStatus).HasDefaultValue(0);
            entity.Property(e => e.RejectionReason).HasMaxLength(500);
            entity.Property(e => e.ApproverId).HasColumnName("ApproverID");
            entity.Property(e => e.MaterialCode)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("MaterialCode");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpertId).HasColumnName("ExpertID");
            entity.Property(e => e.GradeId).HasColumnName("GradeID");
            entity.Property(e => e.PreviewUrl)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.ResourceUrl)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.SubjectId).HasColumnName("SubjectID");
            entity.Property(e => e.Title).HasMaxLength(200);
            entity.Property(e => e.Type)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Approver).WithMany(p => p.Materials)
                .HasForeignKey(d => d.ApproverId)
                .HasConstraintName("FK__Materials__Appro__5DCAEF64");

            entity.HasOne(d => d.Expert).WithMany(p => p.Materials)
                .HasForeignKey(d => d.ExpertId)
                .HasConstraintName("FK__Materials__Exper__5CD6CB2B");

            entity.HasOne(d => d.Grade).WithMany(p => p.Materials)
                .HasForeignKey(d => d.GradeId)
                .HasConstraintName("FK__Materials__Grade__5FB337D6");

            entity.HasOne(d => d.Subject).WithMany(p => p.Materials)
                .HasForeignKey(d => d.SubjectId)
                .HasConstraintName("FK__Materials__Subje__5EBF139D");
        });

        modelBuilder.Entity<Orders>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Orders__C3905BAF4B2255D1");

            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.OrderDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PaymentMethod)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Status).HasDefaultValue(0);
            entity.Property(e => e.TeacherId).HasColumnName("TeacherID");
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(18, 2)");

            entity.HasOne(d => d.Teacher).WithMany(p => p.Orders)
                .HasForeignKey(d => d.TeacherId)
                .HasConstraintName("FK__Orders__TeacherI__08B54D69");
        });

        modelBuilder.Entity<Products>(entity =>
        {
            entity.HasKey(e => e.ProductId).HasName("PK__Products__B40CC6ED21E0E3A0");

            entity.HasIndex(e => new { e.ProductId, e.TeacherId }, "UQ_Products_Teacher").IsUnique();

            entity.Property(e => e.ProductId).HasColumnName("ProductID");
            entity.Property(e => e.ProductCode)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ProductCode");
            entity.Property(e => e.ProductName).HasMaxLength(200);
            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.SourceInputId).HasColumnName("SourceInputID");
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.TeacherId).HasColumnName("TeacherID");
            entity.Property(e => e.EvaluationResult).HasColumnType("nvarchar(max)");
            entity.Property(e => e.EvaluatedAt).HasColumnType("datetime");
            entity.Property(e => e.LessonPlanText).HasColumnType("nvarchar(max)");
            entity.Property(e => e.SlideDocument).HasColumnType("nvarchar(max)");
            entity.Property(e => e.SlideGeneratedAt).HasColumnType("datetime");
            entity.Property(e => e.SlideEditedDocument).HasColumnType("nvarchar(max)");
            entity.Property(e => e.SlideEditedAt).HasColumnType("datetime2");

            entity.HasOne(d => d.Project).WithMany(p => p.Products)
                .HasForeignKey(d => d.ProjectId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Products__Projec__6EF57B66");

            entity.HasOne(d => d.Teacher).WithMany(p => p.Products)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Products__Teache__6FE99F9F");
        });

        modelBuilder.Entity<ProductVideos>(entity =>
        {
            entity.HasKey(e => e.ProductVideoId).HasName("PK_ProductVideos");

            entity.HasIndex(e => new { e.ProductId, e.CreatedAt }, "IX_ProductVideos_ProductId_CreatedAt");
            entity.HasIndex(e => e.ProductVideoCode, "UQ_ProductVideos_ProductVideoCode").IsUnique();

            entity.Property(e => e.ProductVideoId).HasColumnName("ProductVideoId");
            entity.Property(e => e.ProductId).HasColumnName("ProductId");
            entity.Property(e => e.ProductVideoCode)
                .HasMaxLength(200)
                .IsUnicode(false);
            entity.Property(e => e.VideoName).HasMaxLength(200);
            entity.Property(e => e.Status)
                .HasDefaultValue(0);
            entity.Property(e => e.SlideDocumentUrl).HasMaxLength(1000);
            entity.Property(e => e.VideoUrl).HasMaxLength(1000);
            entity.Property(e => e.Duration).HasColumnType("float");
            entity.Property(e => e.Interactions).HasColumnType("nvarchar(max)");
            entity.Property(e => e.ErrorMessage).HasMaxLength(2000);
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime2")
                .HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime2");
            entity.Property(e => e.CompletedAt).HasColumnType("datetime2");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductVideos)
                .HasForeignKey(d => d.ProductId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_ProductVideos_Products");
        });

        modelBuilder.Entity<Projects>(entity =>
        {
            entity.HasKey(e => e.ProjectId).HasName("PK__Projects__761ABED03237E04E");

            entity.Property(e => e.ProjectId).HasColumnName("ProjectID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("GETUTCDATE()")
                .HasColumnType("datetime2");
            entity.Property(e => e.ProjectCode)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("ProjectCode");
            entity.Property(e => e.ProjectName).HasMaxLength(200);
            entity.Property(e => e.SubjectId).HasColumnName("SubjectID");
            entity.Property(e => e.GradeId).HasColumnName("GradeID");
            entity.Property(e => e.Status).HasDefaultValue(0);
            entity.Property(e => e.TeacherId).HasColumnName("TeacherID");

            entity.HasOne(d => d.Teacher).WithMany(p => p.Projects)
                .HasForeignKey(d => d.TeacherId)
                .HasConstraintName("FK__Projects__Teache__68487DD7");

            entity.HasOne(d => d.Subject).WithMany(p => p.Projects)
                .HasForeignKey(d => d.SubjectId)
                .HasConstraintName("FK_Projects_Subjects");

            entity.HasOne(d => d.Grade).WithMany(p => p.Projects)
                .HasForeignKey(d => d.GradeId)
                .HasConstraintName("FK_Projects_Grades");
        });

        modelBuilder.Entity<Roles>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Roles__8AFACE3ADD4643BD");

            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Staffs>(entity =>
        {
            entity.HasKey(e => e.StaffId).HasName("PK__Staffs__96D4AAF751264458");

            entity.HasIndex(e => e.StaffCode, "UQ__Staffs__D83AD812B1EC83D6").IsUnique();

            entity.Property(e => e.StaffId)
                .ValueGeneratedNever()
                .HasColumnName("StaffID");
            entity.Property(e => e.Department).HasMaxLength(100);
            entity.Property(e => e.StaffCode)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Staff).WithOne(p => p.Staffs)
                .HasForeignKey<Staffs>(d => d.StaffId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Staffs_Users");
        });

        modelBuilder.Entity<Subjects>(entity =>
        {
            entity.HasKey(e => e.SubjectId).HasName("PK__Subjects__AC1BA38865AA8D90");

            entity.Property(e => e.SubjectId).HasColumnName("SubjectID");
            entity.Property(e => e.SubjectCode)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("SubjectCode");
            entity.Property(e => e.SubjectName).HasMaxLength(100);
        });

        modelBuilder.Entity<QuotaPlans>(entity =>
        {
            entity.HasKey(e => e.PlanId).HasName("PK__Subscrip__755C22D74FC00743");

            entity.Property(e => e.PlanId).HasColumnName("PlanID");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.PlanName).HasMaxLength(100);
            entity.Property(e => e.Price).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.AnalysisQuotaAmount).HasDefaultValue(0);
            entity.Property(e => e.SlideQuotaAmount).HasDefaultValue(0);
            entity.Property(e => e.VideoQuotaAmount).HasDefaultValue(0);
            entity.Property(e => e.GameQuotaAmount).HasDefaultValue(0);
        });

        modelBuilder.Entity<TeacherMaterials>(entity =>
        {
            entity.HasKey(e => new { e.TeacherId, e.MaterialId }).HasName("PK__TeacherM__81A2387567765723");

            entity.Property(e => e.TeacherId).HasColumnName("TeacherID");
            entity.Property(e => e.MaterialId).HasColumnName("MaterialID");
            entity.Property(e => e.PurchasedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Material).WithMany(p => p.TeacherMaterials)
                .HasForeignKey(d => d.MaterialId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TeacherMa__Mater__6477ECF3");

            entity.HasOne(d => d.Teacher).WithMany(p => p.TeacherMaterials)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__TeacherMa__Teach__6383C8BA");
        });

        modelBuilder.Entity<Teachers>(entity =>
        {
            entity.HasKey(e => e.TeacherId).HasName("PK__Teachers__EDF25944C8B89D82");

            entity.HasIndex(e => e.TeacherCode, "UQ__Teachers__TeacherCode").IsUnique();

            entity.Property(e => e.TeacherId)
                .ValueGeneratedNever()
                .HasColumnName("TeacherID");
            entity.Property(e => e.TeacherCode)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.SchoolName).HasMaxLength(100);

            entity.HasOne(d => d.Teacher).WithOne(p => p.Teachers)
                .HasForeignKey<Teachers>(d => d.TeacherId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Teachers_Users");
        });

        modelBuilder.Entity<UserQuotas>(entity =>
        {
            entity.HasKey(e => e.UserQuotaId).HasName("PK__UserQuot__94C6F707A1BAB374");

            entity.HasIndex(e => e.TeacherId, "UQ__UserQuot__EDF25945AE47A83B").IsUnique();

            entity.Property(e => e.UserQuotaId).HasColumnName("UserQuotaID");
            entity.Property(e => e.AvailableAnalysisQuota).HasDefaultValue(0);
            entity.Property(e => e.AvailableSlideQuota).HasDefaultValue(0);
            entity.Property(e => e.AvailableVideoQuota).HasDefaultValue(0);
            entity.Property(e => e.TeacherId).HasColumnName("TeacherID");
            entity.Property(e => e.TotalAnalysisQuota).HasDefaultValue(0);
            entity.Property(e => e.TotalSlideQuota).HasDefaultValue(0);
            entity.Property(e => e.TotalVideoQuota).HasDefaultValue(0);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UsedAnalysisQuota).HasDefaultValue(0);
            entity.Property(e => e.UsedSlideQuota).HasDefaultValue(0);
            entity.Property(e => e.UsedVideoQuota).HasDefaultValue(0);
            entity.Property(e => e.TotalGameQuota).HasDefaultValue(0);
            entity.Property(e => e.AvailableGameQuota).HasDefaultValue(0);
            entity.Property(e => e.UsedGameQuota).HasDefaultValue(0);

            entity.HasOne(d => d.Teacher).WithOne(p => p.UserQuotas)
                .HasForeignKey<UserQuotas>(d => d.TeacherId)
                .HasConstraintName("FK__UserQuota__Teach__03F0984C");
        });

        modelBuilder.Entity<Users>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCAC75DD0666");

            entity.HasIndex(e => e.Email, "IX_Users_Email");

            entity.HasIndex(e => e.Username, "UQ__Users__536C85E49221B0F6").IsUnique();

            entity.HasIndex(e => e.Email, "UQ__Users__A9D10534C19D49D1").IsUnique();

            entity.HasIndex(e => e.UserCode, "UQ__Users__UserCode").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.UserCode)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.AvatarUrl)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("AvatarURL");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.FullName).HasMaxLength(100);
            entity.Property(e => e.PasswordHash)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.PhoneNumber)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.Status).HasDefaultValue(1);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Users_Roles");
        });

        modelBuilder.Entity<Wallets>(entity =>
        {
            entity.HasKey(e => e.WalletId).HasName("PK__Wallets__84D4F92EAE7BB1F6");

            entity.HasIndex(e => e.UserId, "UQ__Wallets__1788CCADD1E95214").IsUnique();

            entity.Property(e => e.WalletId).HasColumnName("WalletID");
            entity.Property(e => e.Balance)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LastUpdated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.User).WithOne(p => p.Wallets)
                .HasForeignKey<Wallets>(d => d.UserId)
                .HasConstraintName("FK__Wallets__UserID__797309D9");
        });

        modelBuilder.Entity<WalletTransactions>(entity =>
        {
            entity.HasKey(e => e.TransactionId).HasName("PK__WalletTransactions__TransactionId");

            entity.HasIndex(e => e.OrderCode, "UQ__WalletTransactions__OrderCode").IsUnique();

            entity.Property(e => e.TransactionId).HasColumnName("TransactionID");
            entity.Property(e => e.WalletId).HasColumnName("WalletID");
            entity.Property(e => e.OrderCode).HasColumnName("OrderCode");
            entity.Property(e => e.TransactionType)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.BalanceBefore).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.BalanceAfter).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Status).HasDefaultValue(0);
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.PlanId).HasColumnName("PlanID");
            entity.Property(e => e.MaterialId).HasColumnName("MaterialId");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasOne(d => d.Wallet).WithMany()
                .HasForeignKey(d => d.WalletId)
                .HasConstraintName("FK__WalletTrans__WalletID");

            entity.HasOne(d => d.Plan).WithMany()
                .HasForeignKey(d => d.PlanId)
                .HasConstraintName("FK__WalletTrans__PlanID");

            entity.HasOne(d => d.Material).WithMany(p => p.WalletTransactions)
                .HasForeignKey(d => d.MaterialId)
                .HasConstraintName("FK_WalletTransactions_Materials");
        });

        modelBuilder.Entity<CurriculumDocuments>(entity =>
        {
            entity.HasKey(e => e.CurriculumDocumentId).HasName("PK_CurriculumDocuments");

            entity.HasIndex(e => e.DocumentCode, "UQ_CurriculumDocuments_DocumentCode").IsUnique();

            entity.Property(e => e.CurriculumDocumentId).HasColumnName("CurriculumDocumentId");
            entity.Property(e => e.DocumentCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.SubjectCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.EducationLevel)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.OriginalFileName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FileUrl)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Status).HasDefaultValue(0);
            entity.Property(e => e.Note).HasColumnType("nvarchar(max)");
            entity.Property(e => e.Stats).HasColumnType("nvarchar(max)");
            entity.Property(e => e.ErrorMessage).HasColumnType("nvarchar(max)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("GETUTCDATE()")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<WithdrawalRequests>(entity =>
        {
            entity.HasKey(e => e.WithdrawalId).HasName("PK_WithdrawalRequests");

            entity.ToTable("WithdrawalRequests");

            entity.Property(e => e.Amount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.LockedAmount).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.BankAccountNumber).HasMaxLength(30);
            entity.Property(e => e.BankName).HasMaxLength(100);
            entity.Property(e => e.AccountHolderName).HasMaxLength(100);
            entity.Property(e => e.Status)
                .HasDefaultValue(0);
            entity.Property(e => e.AdminNote).HasMaxLength(500);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("GETUTCDATE()")
                .HasColumnType("datetime");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime");

            entity.HasIndex(e => e.UserId, "IX_WithdrawalRequests_UserId");
            entity.HasIndex(e => e.Status, "IX_WithdrawalRequests_Status");

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WithdrawalRequests_Users");

            entity.HasOne(d => d.ProcessedByAdmin).WithMany()
                .HasForeignKey(d => d.ProcessedByAdminId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WithdrawalRequests_Admins");
        });

        modelBuilder.Entity<StudentLists>(entity =>
        {
            entity.ToTable("StudentLists");

            entity.HasKey(e => e.StudentListId).HasName("PK_StudentLists");

            entity.HasIndex(e => e.StudentListCode, "UQ_StudentLists_StudentListCode").IsUnique();
            entity.HasIndex(e => e.TeacherId, "IX_StudentLists_TeacherID");

            entity.Property(e => e.StudentListId).HasColumnName("StudentListID");
            entity.Property(e => e.StudentListCode).HasMaxLength(100).IsUnicode(false);
            entity.Property(e => e.TeacherId).HasColumnName("TeacherID");
            entity.Property(e => e.Description).HasMaxLength(500);
            entity.Property(e => e.Students).HasColumnType("nvarchar(max)");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime2")
                .HasDefaultValueSql("GETUTCDATE()");
            entity.Property(e => e.UpdatedAt).HasColumnType("datetime2");

            entity.HasOne(d => d.Teacher).WithMany(p => p.StudentLists)
                .HasForeignKey(d => d.TeacherId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_StudentLists_Teachers");
        });

        modelBuilder.Entity<TextbookDocuments>(entity =>
        {
            entity.HasKey(e => e.TextbookDocumentId).HasName("PK_TextbookDocuments");

            entity.HasIndex(e => e.DocumentCode, "UQ_TextbookDocuments_DocumentCode").IsUnique();

            entity.Property(e => e.TextbookDocumentId).HasColumnName("TextbookDocumentID");
            entity.Property(e => e.DocumentCode)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.SubjectCode)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.GradeCode)
                .IsRequired()
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Publisher).HasMaxLength(200);
            entity.Property(e => e.OriginalFileName)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.FileUrl)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Status).HasDefaultValue(0);
            entity.Property(e => e.Note).HasColumnType("nvarchar(max)");
            entity.Property(e => e.Stats).HasColumnType("nvarchar(max)");
            entity.Property(e => e.ErrorMessage).HasColumnType("nvarchar(max)");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("GETUTCDATE()")
                .HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}