// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class Admins
{
    public int AdminId { get; set; }

    public virtual Users Admin { get; set; }
}