// <auto-generated> This file has been manually added to support card templates. </auto-generated>
#nullable disable
using System;

namespace EduVi.Repositories.Models;

public partial class CardTemplates
{
    public int TemplateId { get; set; }

    public string TemplateCode { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string Category { get; set; }

    public string Skeleton { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }
}
