// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class Chapters
{
    public int ChapterId { get; set; }

    public int? SubjectId { get; set; }

    public string ChapterName { get; set; }

    public virtual ICollection<InputDocuments> InputDocuments { get; set; } = new List<InputDocuments>();

    public virtual Subjects Subject { get; set; }
}