// <auto-generated> This file has been manually added to support Classroom feature. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class Classrooms
{
    public int ClassroomId { get; set; }

    /// <summary>Format: cls_{teacherId}_{yyyyMMddHHmmss}</summary>
    public string ClassroomCode { get; set; }

    public int TeacherId { get; set; }

    public string Name { get; set; }

    /// <summary>Tên lớp hiển thị, ví dụ "10A1", "11B2"</summary>
    public string GradeLabel { get; set; }

    /// <summary>Năm học, ví dụ "2024-2025"</summary>
    public string SchoolYear { get; set; }

    /// <summary>
    /// Danh sách học sinh lưu dưới dạng JSON array tên hiển thị.
    /// VD: ["Nguyễn Văn A", "Trần Thị B"]
    /// </summary>
    public string Students { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Teachers Teacher { get; set; }
}
