// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class Experts
{
    public int ExpertId { get; set; }

    public string ExpertCode { get; set; }

    public string Bio { get; set; }

    public string IdentityCardNumber { get; set; }

    public string TaxCode { get; set; }

    public string BankAccount { get; set; }

    public string BankName { get; set; }

    public bool? IsVerified { get; set; }

    public virtual Users Expert { get; set; }

    public virtual ICollection<Materials> Materials { get; set; } = new List<Materials>();
}