// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class GameTemplates
{
    public string TemplateId { get; set; }

    public string TemplateCode { get; set; }

    public string TemplateJson { get; set; }
}
