// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class Grades
{
    public int GradeId { get; set; }

    public string GradeCode { get; set; }

    public string GradeName { get; set; }

    public virtual ICollection<InputDocuments> InputDocuments { get; set; } = new List<InputDocuments>();

    public virtual ICollection<Projects> Projects { get; set; } = new List<Projects>();

    public virtual ICollection<Materials> Materials { get; set; } = new List<Materials>();
}