// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class InputDocuments
{
    public int DocumentId { get; set; }

    public int? TeacherId { get; set; }

    public int? SubjectId { get; set; }

    public int? GradeId { get; set; }

    public int? ChapterId { get; set; }

    public string Raw { get; set; }

    public string Title { get; set; }

    public string FilePath { get; set; }

    public DateTime? UploadDate { get; set; }

    public virtual Chapters Chapter { get; set; }

    public virtual Grades Grade { get; set; }

    public virtual ICollection<Projects> Projects { get; set; } = new List<Projects>();

    public virtual Subjects Subject { get; set; }

    public virtual Teachers Teacher { get; set; }
}