// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class Lessons
{
    public int LessonId { get; set; }

    public int? SubjectId { get; set; }

    public string LessonCode { get; set; }

    public string LessonName { get; set; }

    public virtual ICollection<InputDocuments> InputDocuments { get; set; } = new List<InputDocuments>();

    public virtual Subjects Subject { get; set; }
}
