// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class Materials
{
    public int MaterialId { get; set; }

    public int? ExpertId { get; set; }

    public int? SubjectId { get; set; }

    public int? GradeId { get; set; }

    public string MaterialCode { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Type { get; set; }

    public decimal? Price { get; set; }

    public string ResourceUrl { get; set; }

    public string PreviewUrl { get; set; }

    /// <summary>0 = Pending, 1 = Approved, 2 = Rejected</summary>
    public int? ApprovalStatus { get; set; }

    public string RejectionReason { get; set; }

    public int? ApproverId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Staffs Approver { get; set; }

    public virtual Experts Expert { get; set; }

    public virtual Grades Grade { get; set; }

    public virtual Subjects Subject { get; set; }

    public virtual ICollection<ProductMaterials> ProductMaterials { get; set; } = new List<ProductMaterials>();

    public virtual ICollection<TeacherMaterials> TeacherMaterials { get; set; } = new List<TeacherMaterials>();

    public virtual ICollection<WalletTransactions> WalletTransactions { get; set; } = new List<WalletTransactions>();
}