// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class Orders
{
    public int OrderId { get; set; }

    public int? TeacherId { get; set; }

    public decimal? TotalAmount { get; set; }

    public DateTime? OrderDate { get; set; }

    /// <summary>0 = Pending, 1 = Completed, 2 = Failed, 3 = Cancelled</summary>
    public int? Status { get; set; }

    public string PaymentMethod { get; set; }

    public virtual Teachers Teacher { get; set; }
}