// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class Products
{
    public int ProductId { get; set; }

    public int ProjectId { get; set; }

    public int TeacherId { get; set; }

    public string ProductCode { get; set; }

    public string ProductName { get; set; }

    public string Description { get; set; }

    public int? SourceInputId { get; set; }

    /// <summary>0 = New, 1 = Processing, 2 = Evaluated, 3 = Failed, 4 = GeneratingSlides, 5 = SlidesGenerated, 6 = SlidesFailed, 7 = Deleted — xem ProductStatusConstants</summary>
    public int? Status { get; set; }

    public string EvaluationResult { get; set; }

    public DateTime? EvaluatedAt { get; set; }

    public string LessonPlanText { get; set; }

    public string SlideDocument { get; set; }

    public DateTime? SlideGeneratedAt { get; set; }

    public string SlideEditedDocument { get; set; }

    public DateTime? SlideEditedAt { get; set; }

    public virtual ICollection<ProductVideos> ProductVideos { get; set; } = new List<ProductVideos>();

    public virtual Projects Project { get; set; }

    public virtual Teachers Teacher { get; set; }
}