// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class ProductMaterials
{
    public int ProductMaterialId { get; set; }

    public int ProductId { get; set; }

    public int? MaterialId { get; set; }

    public string ProductMaterialCode { get; set; }

    /// <summary>Marketplace | Upload</summary>
    public string SourceType { get; set; }

    public string Title { get; set; }

    public string Type { get; set; }

    public string ResourceUrl { get; set; }

    public string PreviewUrl { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Materials Material { get; set; }

    public virtual Products Product { get; set; }
}
