// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class ProductComponent
{
    public int ProductId { get; set; }

    public int MaterialId { get; set; }

    public int TeacherId { get; set; }

    public string ComponentCode { get; set; }

    public string CardId { get; set; }

    public string BlockId { get; set; }

    public DateTime AddedAt { get; set; }

    public virtual Products Products { get; set; }

    public virtual TeacherMaterials TeacherMaterials { get; set; }
}