// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class ProductComponent
{
    public int ProductId { get; set; }

    public int MaterialId { get; set; }

    public int TeacherId { get; set; }

    public string ComponentCode { get; set; }

    /// <summary>
    /// ID của Card trong SlideEditedDocument JSON mà material này được chèn vào.
    /// e.g. "card-acf4c8be". Null nếu chưa xác định vị trí.
    /// </summary>
    public string CardId { get; set; }

    /// <summary>
    /// ID của Block trong Card mà material này được chèn vào.
    /// e.g. "block-media-001". Null nếu chưa xác định vị trí.
    /// </summary>
    public string BlockId { get; set; }

    /// <summary>
    /// Thời điểm Teacher thêm material này vào slide.
    /// </summary>
    public DateTime AddedAt { get; set; }

    public virtual Products Products { get; set; }

    public virtual TeacherMaterials TeacherMaterials { get; set; }
}