// <auto-generated> This file has been manually added to support video pipeline. </auto-generated>
#nullable disable
using System;

namespace EduVi.Repositories.Models;

public partial class ProductVideos
{
    public int ProductVideoId { get; set; }

    public int ProductId { get; set; }

    public string ProductVideoCode { get; set; }

    /// <summary>0 = Queued, 1 = Completed, 2 = Failed, 3 = Deleted — xem VideoStatusConstants</summary>
    public int Status { get; set; }

    public string SlideDocumentUrl { get; set; }

    public string VideoUrl { get; set; }

    public double? Duration { get; set; }

    public string Interactions { get; set; }

    public string ErrorMessage { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public virtual Products Product { get; set; }
}
