// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class Projects
{
    public int ProjectId { get; set; }

    public int? TeacherId { get; set; }

    public string ProjectCode { get; set; }

    public string ProjectName { get; set; }

    public int? SubjectId { get; set; }

    public int? GradeId { get; set; }

    public int? Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<InputDocuments> InputDocuments { get; set; } = new List<InputDocuments>();

    public virtual ICollection<Products> Products { get; set; } = new List<Products>();

    public virtual Subjects Subject { get; set; }

    public virtual Grades Grade { get; set; }

    public virtual Teachers Teacher { get; set; }
}