// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class Staffs
{
    public int StaffId { get; set; }

    public string StaffCode { get; set; }

    public string Department { get; set; }

    public DateOnly? HireDate { get; set; }

    public virtual ICollection<Materials> Materials { get; set; } = new List<Materials>();

    public virtual Users Staff { get; set; }
}