// <auto-generated> This file has been manually added to support StudentList feature. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class StudentLists
{
    public int StudentListId { get; set; }

    /// <summary>Format: sls_{teacherId}_{yyyyMMddHHmmss}</summary>
    public string StudentListCode { get; set; }

    public int TeacherId { get; set; }

    public string Description { get; set; }

    /// <summary>
    /// Danh sách học sinh lưu dưới dạng JSON array tên hiển thị.
    /// VD: ["Nguyễn Văn A", "Trần Thị B"]
    /// </summary>
    public string Students { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Teachers Teacher { get; set; }
}
