// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class Subjects
{
    public int SubjectId { get; set; }

    public string SubjectName { get; set; }

    public string Code { get; set; }

    public virtual ICollection<Chapters> Chapters { get; set; } = new List<Chapters>();

    public virtual ICollection<InputDocuments> InputDocuments { get; set; } = new List<InputDocuments>();

    public virtual ICollection<Materials> Materials { get; set; } = new List<Materials>();
}