// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class Subjects
{
    public int SubjectId { get; set; }

    public string SubjectName { get; set; }

    public string SubjectCode { get; set; }

    public virtual ICollection<Lessons> Lessons { get; set; } = new List<Lessons>();

    public virtual ICollection<InputDocuments> InputDocuments { get; set; } = new List<InputDocuments>();

    public virtual ICollection<Materials> Materials { get; set; } = new List<Materials>();
}