// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class SubscriptionPlans
{
    public int PlanId { get; set; }

    public string PlanName { get; set; }

    public decimal? Price { get; set; }

    public int? DurationDays { get; set; }

    public int? AnalysisQuotaAmount { get; set; }

    public int? SlideQuotaAmount { get; set; }

    public int? VideoQuotaAmount { get; set; }

    public string Description { get; set; }

    public bool? IsActive { get; set; }
}