// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class SystemLogs
{
    public long LogId { get; set; }

    public int? UserId { get; set; }

    public string Action { get; set; }

    public string Ipaddress { get; set; }

    public DateTime? Timestamp { get; set; }

    public virtual Users User { get; set; }
}