// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class Teachers
{
    public int TeacherId { get; set; }

    public string TeacherCode { get; set; }

    public string SchoolName { get; set; }

    public string Degree { get; set; }

    public virtual ICollection<InputDocuments> InputDocuments { get; set; } = new List<InputDocuments>();

    public virtual ICollection<Orders> Orders { get; set; } = new List<Orders>();

    public virtual ICollection<Products> Products { get; set; } = new List<Products>();

    public virtual ICollection<Projects> Projects { get; set; } = new List<Projects>();

    public virtual Users Teacher { get; set; }

    public virtual ICollection<TeacherMaterials> TeacherMaterials { get; set; } = new List<TeacherMaterials>();

    public virtual UserQuotas UserQuotas { get; set; }
}