// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class TeacherMaterials
{
    public int TeacherId { get; set; }

    public int MaterialId { get; set; }

    public DateTime? PurchasedDate { get; set; }

    public virtual Materials Material { get; set; }

    public virtual ICollection<ProductComponent> ProductComponent { get; set; } = new List<ProductComponent>();

    public virtual Teachers Teacher { get; set; }
}