// <auto-generated> This file has been manually added to support generated games persistence. </auto-generated>
#nullable disable
using System;

namespace EduVi.Repositories.Models;

public partial class TeacherGames
{
    public int TeacherGameId { get; set; }

    public int TeacherId { get; set; }

    public string TeacherGameCode { get; set; }

    public Guid TaskId { get; set; }

    public string GameName { get; set; }

    public string TemplateCode { get; set; }

    public int RoundCount { get; set; }

    /// <summary>0 = Queued, 1 = Completed, 2 = Failed, 3 = Deleted — xem GameStatusConstants</summary>
    public int Status { get; set; }

    public string ResultJson { get; set; }

    public string ErrorMessage { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public virtual Teachers Teacher { get; set; }
}