// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class UserQuotas
{
    public int UserQuotaId { get; set; }

    public int? TeacherId { get; set; }

    public int? TotalAnalysisQuota { get; set; }

    public int? AvailableAnalysisQuota { get; set; }

    public int? UsedAnalysisQuota { get; set; }

    public int? TotalSlideQuota { get; set; }

    public int? AvailableSlideQuota { get; set; }

    public int? UsedSlideQuota { get; set; }

    public int? TotalVideoQuota { get; set; }

    public int? AvailableVideoQuota { get; set; }

    public int? UsedVideoQuota { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Teachers Teacher { get; set; }
}