// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class UserQuotas
{
    public int UserQuotaId { get; set; }

    public int? TeacherId { get; set; }

    public int? TotalQuota { get; set; }

    public int? AvailableQuota { get; set; }

    public int? UsedQuota { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual Teachers Teacher { get; set; }
}