// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduVi.Repositories.Models;

public partial class Users
{
    public int UserId { get; set; }

    public string UserCode { get; set; }

    public string Username { get; set; }

    public string PasswordHash { get; set; }

    public string Email { get; set; }

    public string FullName { get; set; }

    public string PhoneNumber { get; set; }

    public string AvatarUrl { get; set; }

    /// <summary>0 = Banned, 1 = Active</summary>
    public int? Status { get; set; }

    public bool IsEmailVerified { get; set; }

    public DateTime? CreatedAt { get; set; }

    public int RoleId { get; set; }

    public virtual Admins Admins { get; set; }

    public virtual Experts Experts { get; set; }

    public virtual Roles Role { get; set; }

    public virtual Staffs Staffs { get; set; }

    public virtual ICollection<SystemLogs> SystemLogs { get; set; } = new List<SystemLogs>();

    public virtual Teachers Teachers { get; set; }

    public virtual Wallets Wallets { get; set; }
}